root = "." # The root directory of the project
tmp_dir = "tmp" # The temp directory of where air will store temp files

[build]
  bin = "main" # The name of the binary file to be generated after building the project
  cmd = "go build -o {{.Output}} {{.Input}}" # The command to build the project
  exclude = ["tmp/*", "client/*"] # Specific directories to be excluded from monitoring changes
  include = ["**/*.go"] # Specific file patterns to be included for monitoring
  ignore = ["tmp/*"] # Specific files or directories to be ignored when trigering a build
