openapi: 3.0.3
info:
  title: Skilltrade API
  description: API for facilitating exchange of skills between creatives.
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /users:
    post:
      summary: Add a new user
      operationId: CreateUserHandler
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInput"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error

  /users/{id}:
    put:
      summary: Update a user's fields by ID
      operationId: UpdateUserHandler
      parameters:
        - name: id
          in: path
          required: true
          description: The UUID of the user to delete
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInput"
      responses:
        "200":
          description: User successfully updated
        "400":
          description: Invalid user ID
        "404":
          description: User not found
        "500":
          description: Internal Server Error (Unexpected failure)

  /users/del/{id}:
    delete:
      summary: Delete a user by ID
      operationId: DeleteUserHandler
      parameters:
        - name: id
          in: path
          required: true
          description: The UUID of the user to delete
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: User successfully deleted
        "400":
          description: Invalid user ID
        "404":
          description: User not found
        "500":
          description: Internal Server Error (Unexpected failure)

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique user ID.
        email:
          type: string
          format: email
          description: User's email address.
        password:
          type: string
          minLength: 8
          pattern: '^(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$'
          description: User's password.
        full_name:
          type: string
          description: User's full name.
        created_at:
          type: string
          format: date-time
          description: Timestamp when user was created (ISO 8601 format).

    UserInput:
      type: object
      required:
        - email
        - password
        - full_name
      properties:
        email:
          type: string
          format: email
          description: User's email address.
        password:
          type: string
          minLength: 8
          pattern: '^(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$'
          description: User's password.
        full_name:
          type: string
          description: User's full name.
